// <auto-generated />
using System;
using DataCatalogMini.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataCatalogMini.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102120553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataCatalogMini.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2025, 10, 28, 12, 5, 52, 924, DateTimeKind.Utc).AddTicks(4515),
                            Name = "Customer_Records",
                            Owner = "Data Governance",
                            TechnologyId = 1,
                            Type = "Table"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(2025, 10, 31, 12, 5, 52, 924, DateTimeKind.Utc).AddTicks(4520),
                            Name = "Transactions_Stream",
                            Owner = "Core Banking",
                            TechnologyId = 3,
                            Type = "Topic"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = new DateTime(2025, 11, 1, 12, 5, 52, 924, DateTimeKind.Utc).AddTicks(4521),
                            Name = "HR_Employees",
                            Owner = "HR Department",
                            TechnologyId = 2,
                            Type = "Table"
                        });
                });

            modelBuilder.Entity("DataCatalogMini.Models.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("ChangeLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            ChangeDate = new DateTime(2025, 10, 30, 12, 5, 52, 924, DateTimeKind.Utc).AddTicks(4532),
                            Description = "Column added: customer_status",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            ChangeDate = new DateTime(2025, 11, 1, 12, 5, 52, 924, DateTimeKind.Utc).AddTicks(4534),
                            Description = "New partition policy applied",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DataCatalogMini.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kafka"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SAP HANA"
                        });
                });

            modelBuilder.Entity("DataCatalogMini.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "1234",
                            Role = "User",
                            Username = "onur"
                        });
                });

            modelBuilder.Entity("DataCatalogMini.Models.Asset", b =>
                {
                    b.HasOne("DataCatalogMini.Models.Technology", "Technology")
                        .WithMany("Assets")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("DataCatalogMini.Models.ChangeLog", b =>
                {
                    b.HasOne("DataCatalogMini.Models.Asset", "Asset")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCatalogMini.Models.User", "User")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataCatalogMini.Models.Asset", b =>
                {
                    b.Navigation("ChangeLogs");
                });

            modelBuilder.Entity("DataCatalogMini.Models.Technology", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("DataCatalogMini.Models.User", b =>
                {
                    b.Navigation("ChangeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
